CREATE SCHEMA IF NOT EXISTS helpdesk;

CREATE TABLE helpdesk.categoria_ticket (
    id bigint NOT NULL,
    nombre character varying(150),
    descripcion text,
    estado_registro character varying(20) DEFAULT 'ACTIVO'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_modificacion timestamp without time zone,
    CONSTRAINT chk_categoria_estado_registro CHECK (((estado_registro)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);

ALTER TABLE helpdesk.categoria_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.categoria_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE helpdesk.departamento (
    id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    descripcion text,
    estado_registro character varying(20) DEFAULT 'ACTIVO'::character varying NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_modificacion timestamp without time zone,
    CONSTRAINT chk_departamento_estado_registro CHECK (((estado_registro)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);

ALTER TABLE helpdesk.departamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.departamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE helpdesk.rol (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    estado_registro character varying(20) DEFAULT 'ACTIVO'::character varying NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_modificacion timestamp without time zone,
    CONSTRAINT chk_rol_estado_resgitro CHECK (((estado_registro)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);

ALTER TABLE helpdesk.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE helpdesk.ticket (
    id bigint NOT NULL,
    codigo character varying(50),
    titulo character varying(200),
    descripcion text,
    estado character varying(30) DEFAULT 'REGISTRADO'::character varying,
    prioridad character varying(30) DEFAULT 'MEDIA'::character varying,
    categoria_id bigint,
    departamento_id bigint,
    usuario_creacion bigint,
    usuario_asignado bigint,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_modificacion timestamp without time zone,
    fecha_asignacion timestamp without time zone,
    fecha_inicio_atencion timestamp without time zone,
    fecha_resolucion timestamp without time zone,
    fecha_cierre timestamp without time zone,
    usuario_finalizado bigint,
    solucion text,
    CONSTRAINT chk_ticket_estado CHECK (((estado)::text = ANY ((ARRAY['REGISTRADO'::character varying, 'ASIGNADO'::character varying, 'EN_PROCESO'::character varying, 'RESUELTO'::character varying, 'CERRADO'::character varying, 'ANULADO'::character varying, 'REABIERTO'::character varying])::text[]))),
    CONSTRAINT chk_ticket_prioridad CHECK (((prioridad)::text = ANY ((ARRAY['BAJA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying, 'CRITICA'::character varying])::text[])))
);

CREATE TABLE helpdesk.ticket_adjunto (
    id bigint NOT NULL,
    ticket_id bigint,
    usuario_creacion bigint,
    nombre_original character varying(200),
    nombre_achivo character varying(200),
    ruta_archivo text,
    tipo_contenido character varying(100),
    tamanio_bytes bigint,
    estado_registro character varying(20) DEFAULT 'ACTIVO'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_adjunto_estado_registro CHECK (((estado_registro)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);

ALTER TABLE helpdesk.ticket_adjunto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.ticket_adjunto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE helpdesk.ticket_comentario (
    id bigint NOT NULL,
    ticket_id bigint,
    usuario_id bigint,
    comentario text,
    tipo character varying(30) DEFAULT 'PUBLICO'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp without time zone,
    CONSTRAINT chk_comentario_tipo CHECK (((tipo)::text = ANY ((ARRAY['PUBLICO'::character varying, 'INTERNO'::character varying, 'SISTEMA'::character varying])::text[])))
);

ALTER TABLE helpdesk.ticket_comentario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.ticket_comentario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE helpdesk.ticket_historial (
    id bigint NOT NULL,
    ticket_id bigint,
    usuario_id bigint,
    accion character varying(50),
    estado_anteior character varying(30),
    estado_nuevo character varying(30),
    prioridad_anterior character varying(30),
    prioridad_nueva character varying(30),
    usuario_asignado_anterior bigint,
    usuario_asignado_nuevo bigint,
    observacion text,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_historial_accion CHECK (((accion)::text = ANY ((ARRAY['CREACION'::character varying, 'ASIGNACION'::character varying, 'CAMBIO_ESTADO'::character varying, 'CAMBIO_PRIORIDAD'::character varying, 'COMENTARIO'::character varying, 'ADJUNTO'::character varying, 'RESOLUCION'::character varying, 'CIERRE'::character varying, 'ANULACION'::character varying, 'REAPERTURA'::character varying])::text[])))
);

ALTER TABLE helpdesk.ticket_historial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.ticket_historial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE helpdesk.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE helpdesk.usuario (
    id bigint NOT NULL,
    rol_id bigint,
    departamento_id bigint,
    nombres character varying(150),
    apellidos character varying(150),
    email character varying(150),
    password_hash text,
    telefono character varying(30),
    estado_registro character varying(20) DEFAULT 'ACTIVO'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion timestamp without time zone,
    CONSTRAINT chk_usuario_estado_registro CHECK (((estado_registro)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying])::text[])))
);

ALTER TABLE helpdesk.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME helpdesk.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE VIEW helpdesk.vw_ticket_listado AS
 SELECT t.id,
    t.codigo,
    t.titulo,
    t.estado,
    t.prioridad,
    t.fecha_creacion,
    t.fecha_asignacion,
    t.fecha_inicio_atencion,
    t.fecha_resolucion,
    t.fecha_cierre,
    c.nombre AS categoria,
    d.nombre AS departamento,
    uc.id AS creado_por_id,
    concat(uc.nombres, '', COALESCE(uc.apellidos)) AS creado_por,
    ua.id AS asignado_a_id,
    concat(ua.nombres, ' ', COALESCE(ua.apellidos)) AS asignado_a
   FROM ((((helpdesk.ticket t
     JOIN helpdesk.categoria_ticket c ON ((c.id = t.categoria_id)))
     LEFT JOIN helpdesk.departamento d ON ((d.id = t.departamento_id)))
     JOIN helpdesk.usuario uc ON ((uc.id = t.usuario_creacion)))
     LEFT JOIN helpdesk.usuario ua ON ((ua.id = t.usuario_asignado)));

ALTER TABLE ONLY helpdesk.categoria_ticket
    ADD CONSTRAINT categoria_ticket_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.departamento
    ADD CONSTRAINT departamento_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.rol
    ADD CONSTRAINT rol_codigo_key UNIQUE (codigo);

ALTER TABLE ONLY helpdesk.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.ticket_adjunto
    ADD CONSTRAINT ticket_adjunto_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT ticket_codigo_key UNIQUE (codigo);

ALTER TABLE ONLY helpdesk.ticket_comentario
    ADD CONSTRAINT ticket_comentario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.ticket_historial
    ADD CONSTRAINT ticket_historial_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);

ALTER TABLE ONLY helpdesk.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);

ALTER TABLE ONLY helpdesk.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

CREATE INDEX idx_adjunto_ticket ON helpdesk.ticket_adjunto USING btree (ticket_id);

CREATE INDEX idx_comentario_ticket ON helpdesk.ticket_comentario USING btree (ticket_id);

CREATE INDEX idx_historial_ticket ON helpdesk.ticket_historial USING btree (ticket_id);

CREATE INDEX idx_ticket_categoria ON helpdesk.ticket USING btree (categoria_id);

CREATE INDEX idx_ticket_departamento ON helpdesk.ticket USING btree (departamento_id);

CREATE INDEX idx_ticket_estado ON helpdesk.ticket USING btree (estado);

CREATE INDEX idx_ticket_fecha_creacion ON helpdesk.ticket USING btree (fecha_creacion);

CREATE INDEX idx_ticket_prioridad ON helpdesk.ticket USING btree (prioridad);

CREATE INDEX idx_ticket_usuario_asignado ON helpdesk.ticket USING btree (usuario_asignado);

CREATE INDEX idx_ticket_usuario_creacion ON helpdesk.ticket USING btree (usuario_creacion);

CREATE INDEX idx_usuario_departamento ON helpdesk.usuario USING btree (departamento_id);

CREATE INDEX idx_usuario_rol ON helpdesk.usuario USING btree (rol_id);

ALTER TABLE ONLY helpdesk.ticket_adjunto
    ADD CONSTRAINT fk_adjunto_ticket FOREIGN KEY (ticket_id) REFERENCES helpdesk.ticket(id) ON DELETE CASCADE;

ALTER TABLE ONLY helpdesk.ticket_adjunto
    ADD CONSTRAINT fk_adjunto_usuario FOREIGN KEY (usuario_creacion) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket_comentario
    ADD CONSTRAINT fk_comentario_ticket FOREIGN KEY (ticket_id) REFERENCES helpdesk.ticket(id) ON DELETE CASCADE;

ALTER TABLE ONLY helpdesk.ticket_comentario
    ADD CONSTRAINT fk_comentario_usuario FOREIGN KEY (usuario_id) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket_historial
    ADD CONSTRAINT fk_historial_ticket FOREIGN KEY (ticket_id) REFERENCES helpdesk.ticket(id) ON DELETE CASCADE;

ALTER TABLE ONLY helpdesk.ticket_historial
    ADD CONSTRAINT fk_historial_usuario FOREIGN KEY (usuario_id) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket_historial
    ADD CONSTRAINT fk_historial_usuario_anterior FOREIGN KEY (usuario_asignado_anterior) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket_historial
    ADD CONSTRAINT fk_historial_usuario_nuevo FOREIGN KEY (usuario_asignado_nuevo) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT fk_ticket_categoria FOREIGN KEY (categoria_id) REFERENCES helpdesk.categoria_ticket(id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT fk_ticket_departamento FOREIGN KEY (departamento_id) REFERENCES helpdesk.departamento(id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT fk_ticket_usuario_asignado FOREIGN KEY (usuario_asignado) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT fk_ticket_usuario_creacion FOREIGN KEY (usuario_creacion) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.ticket
    ADD CONSTRAINT fk_ticket_usuario_finalizado FOREIGN KEY (usuario_finalizado) REFERENCES helpdesk.usuario(id);

ALTER TABLE ONLY helpdesk.usuario
    ADD CONSTRAINT fk_usuario_departamento FOREIGN KEY (departamento_id) REFERENCES helpdesk.departamento(id);

ALTER TABLE ONLY helpdesk.usuario
    ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES helpdesk.rol(id);
